events { }

http {
    upstream webservers {
        server webserver:8000; 
    }

    server {
        listen 80;

        # Only allow access to the web endpoints on localhost (for testing/backup) and the vpn range to limit exposure
        location ^~ /web/ {
            allow 127.0.0.1;
            allow 172.16.0.0/12;
    
            deny all;
    
            proxy_pass http://webservers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Only allow access to the agent endpoints on localhost (for testing/backup) and the inscope subnets to limit exposure
        location ^~ /web/ {
            allow 127.0.0.1;
            allow 10.0.0.0/8;
    
            deny all;
    
            proxy_pass http://webservers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # No other authorized endpoints exist
        #location / {
        #    proxy_pass http://webservers;
        #    proxy_set_header Host $host;
        #    proxy_set_header X-Real-IP $remote_addr;
        #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #    proxy_set_header X-Forwarded-Proto $scheme;
        #}
    }
}