---
- name: Windows | Check for existing users
  ansible.windows.win_user:
    name: "{{ item }}"
    state: present
  loop: "{{ blueteam_users }}"
  register: win_user_audit
  check_mode: yes

- name: Safety | Warn if users exist
  ansible.builtin.pause:
    prompt: "WARNING: One or more Blue Team users already exist on this host. Press ENTER to continue or Ctrl+C to abort."
  when:
    - (win_user_audit.results | selectattr('failed', 'sameas', false) | list | length > 0)
  throttle: 1

- name: Windows | Create Users
  ansible.windows.win_user:
    name: "{{ item }}"
    password: "{{ new_password }}"
    groups: 
      - Administrators
      - Remote Desktop Users
    state: present
  loop: "{{ blueteam_users }}"

- name: Windows | Setup Primary Blueteam User
  ansible.windows.win_user:
    name: "{{ blueteam_users[0] }}"
    groups: []
    account_disabled: yes