---
- name: Linux | Get Password Database
  ansible.builtin.getent:
    database: passwd

- name: Linux | Identify Unauthorized Users
  vars:
    allowed_list: "{{ (blueteam_users + out_of_scope_users + legit_local_admins + legit_local_users) | map('lower') | list }}"
    human_users_list: >-
      {% set users = [] %}
      {% for name, details in getent_passwd.items() %}
        {% if details[1] | int >= 1000 %}
          {% set _ = users.append(name | lower) %}
        {% endif %}
      {% endfor %}
      {{ users }}
  ansible.builtin.set_fact:
    unauthorized_users: "{{ human_users_list | difference(allowed_list) | difference(['nobody', 'nfsnobody']) }}"

- name: Linux | Review Unauthorized Users
  ansible.builtin.pause:
    prompt: |
      [HOST: {{ inventory_hostname }}]
      UNAUTHORIZED USERS FOUND: {{ unauthorized_users | join(', ') }}
      
      Press ENTER to LOCK these accounts or Ctrl+C to abort.
  when: unauthorized_users | length > 0
  throttle: 1

- name: Linux | Find nologin shell path
  ansible.builtin.shell: "which nologin || which false"
  register: nologin_path
  changed_when: false
  when: unauthorized_users | length > 0

- name: Linux | Lock Unauthorized Accounts
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "{{ nologin_path.stdout | default('/sbin/nologin') }}"
    password_lock: yes
  loop: "{{ unauthorized_users }}"
  when: unauthorized_users | length > 0

- name: Linux | Report Results
  ansible.builtin.debug:
    msg: "Successfully locked: {{ unauthorized_users | join(', ') }}"
  when: unauthorized_users | length > 0

#- name: Linux | Rotate Passwords
#  ansible.builtin.user:
#    name: "{{ item }}"
#    password: "{{ new_password | password_hash('sha512') }}"
#  loop: "{{ unauthorized_users }}"