---
- name: Windows Local | Get User List via PowerShell
  ansible.windows.win_powershell:
    script: |
      # Get local users and return only the names in a clean array
      $users = Get-LocalUser | Select-Object -ExpandProperty Name
      return @{ user_list = $users }
  register: pwsh_output

- name: Windows Local | Identify Unauthorized Users
  vars:
    allowed_list: "{{ (blueteam_users + out_of_scope_users + legit_local_admins + legit_local_users) | map('lower') | list }}"
    system_users: "{{ [pwsh_output.user_list] | flatten | map('lower') | list }}"
    ignored_defaults: ['administrator', 'guest', 'defaultaccount', 'wdagutilityaccount']
  ansible.builtin.set_fact:
    unauthorized_users: "{{ system_users | difference(allowed_list) | difference(ignored_defaults) }}"

- name: Windows Local | Review Unauthorized Users
  ansible.builtin.pause:
    prompt: |
      [HOST: {{ inventory_hostname }}]
      UNAUTHORIZED LOCAL USERS: {{ unauthorized_users | join(', ') }}
      
      Press ENTER to DISABLE these accounts.
  when: unauthorized_users | length > 0
  throttle: 1

- name: Windows Local | Disable Unauthorized Accounts
  ansible.windows.win_user:
    name: "{{ item }}"
    account_disabled: yes
  loop: "{{ unauthorized_users }}"
  when: unauthorized_users | length > 0

#- name: Windows Local | Rotate Passwords
#  ansible.windows.win_user:
#    name: "{{ item }}"
#    password: "{{ new_password }}"
#    state: present
#  loop: "{{ found_targets }}"