---
# ansible-playbook stabvest_playbook.yaml -i inventory.yaml -t stabvest_server -vv
- name: Deploy Stabvest Server
  hosts: ansible-controller
  roles:
    - stabvest_server
  tags:
    - stabvest
    - stabvest_server

- name: Deploy Stabvest Client
  hosts: iis-winserv22
  #hosts: testing-ubu24
  roles:
    - stabvest_client
  tags:
    - stabvest
    - stabvest_client

- name: Deploy Stabvest Client Automated (do not touch)
  hosts: all
  roles:
    - stabvest_client
  tags:
    - stabvest_client_auto