---
stabvest_deploy_dir: "/stabvest_server"
#stabvest_deploy_dir_win: "C:\\stabvest_server"
#stabvest_deploy_dir_unix: "/stabvest_server"
stabvest_task_create: true
stabvest_task_name: "stabvest_server"
stabvest_task_interval: 300 #seconds. cron needs this to be an even minutes value (so divisible by 60)
stabvest_agent_executable: "server.py"
stabvest_service_start: true
stabvest_gunicorn_workers: 3


stabvest_host: "192.168.1.18" # public URL of server. is NOT used for starting the server listener (that is always 0.0.0.0)
stabvest_port: 8000

# Derived values can still be overridden if needed
public_url: "https://{{ stabvest_host }}:{{ stabvest_port }}"
logfile: "log.txt"

secret_key: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits,special') }}"
stale_time: 300
default_webhook_sleep_time: 0.25
max_webhook_msg_per_minute: 50
webhook_url: "https://discord.com/api/webhooks/1445146908808188065/1xkiXfsL7ie8i04rGxdMu6nnnzJsVtj188VbHtZT5oBNJIoOYV5VP8lpI-mJhzeNYuYD"
create_test_data: false
authconfig_strict_ip: false
authconfig_strict_user: false
authconfig_create_incident: false
authconfig_log_attempt_successful: true
agent_auth_tokens:
  testtoken:
    added_by: "default"
webgui_users:
  admin:
    password: "admin"
    role: "admin"
  analyst:
    password: "analyst"
    role: "analyst"
  guest:
    password: "guest"
    role: "guest"