---
# Ansible Deployment Vars
#owlet_task_create: false
#owlet_task_name: "owlet"
#owlet_task_interval: 300 #seconds. cron needs this to be an even minutes value (so divisible by 60)
owlet_agent_executable: "agent.py"
owlet_service_start: true
owlet_deploy_dir: "/owlet/{{ owlet_agent_name }}/"
#owlet_deploy_dir: "C:\\owlet{{ owlet_agent_name }}\\"

# Agent Config Vars. You probably need to change these for each deployment.
owlet_agent_name: "ssh"
owlet_auth_token: "testtoken"
owlet_auth_log_path: ""
owlet_auth_parser: ""
owlet_sleeptime: 60
owlet_server_url: "https://127.0.0.1:8000/"
owlet_server_timeout: 5
owlet_debug_print: true

# More Agent Config Options - You probably shouldn't be changing these
owlet_agent_type: "owlet"
owlet_logfile: "log.txt"
owlet_statusfile: "status.txt"
owlet_statefile: "state.json"