---
- name: Windows AD | Perform Users Inscope Tasks
  ansible.builtin.include_tasks: windows.yaml
  when: inventory_hostname == 'fortress'

- name: Windows | Perform Users Inscope Tasks
  ansible.builtin.include_tasks: windows.yaml
  when: ansible_os_family == "Windows"
    
- name: Linux | Perform Users Inscope Tasks
  ansible.builtin.include_tasks: linux.yaml
  when: ansible_os_family != "Windows"