[all]
ubuntu
debian
rocky
alpine

[all:vars]
ansible_user=blackteam
ansible_password=blackteam
ansible_become=yes
ansible_become_method=sudo
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
birdsnest_token=testtoken
birdsnest_host=172.19.0.5:443
birdsnest_host_ip=172.19.0.5

[debian_family]
ubuntu
debian

[rhel_family]
rocky

[alpine_family]
alpine

[debian_family:vars]
admin_group_name=sudo

[rhel_family:vars]
admin_group_name=wheel

[alpine_family:vars]
admin_group_name=wheel
ansible_python_interpreter=/usr/bin/python3