all:
  children:
    ecomm:
      hosts:
        Ubuntu-Ecomm:
          external_ip: "172.16.1.30"
          internal_ip: "172.20.10.30"
          ansible_host: "{{ internal_ip }}"
          os: "Ubuntu Server 24.04"
          default_user: "sysadmin"
          default_password: "Changeme1!"

    webmail:
      hosts:
        Rocky-Webmail:
          external_ip: "172.16.1.40"
          internal_ip: "172.20.10.40"
          ansible_host: "{{ internal_ip }}"
          os: "Rocky Linux 9"
          default_user: "sysadmin"
          default_password: "Changeme1!"

    siem:
      hosts:
        Splunk:
          external_ip: "172.16.1.20"
          internal_ip: "172.20.10.20"
          ansible_host: "{{ internal_ip }}"
          os: "Rocky Linux 9"
          default_user: "sysadmin"
          default_password: "Changeme1!"

    workstations:
      hosts:
        Ubuntu-Wkst:
          external_ip: "172.16.1.50"
          internal_ip: "172.20.10.50"
          ansible_host: "{{ internal_ip }}"
          default_user: "sysadmin"
          default_password: "Changeme1!"

        Win10-Wkst:
          external_ip: "172.16.1.100"
          internal_ip: "172.20.11.100"
          ansible_host: "{{ internal_ip }}"
          default_user: "localuser"
          default_password: "password"

    gateways:
      hosts:
        Alpine-FW:
          external_ip: "172.16.1.1"
          internal_ip: "172.20.10.1"
          ansible_host: "{{ internal_ip }}"
          default_user: "alpine"
          default_password: "alpine"
        OPNsense-FW:
          ansible_host: "172.16.1.2"
          external_ip: "172.16.1.2"
          internal_ip: "172.20.11.1"
          default_user: "root"
          default_password: "opnsense"

    ad_dns:
      hosts:
        AD-DNS:
          external_ip: "172.16.1.102"
          internal_ip: "172.20.11.102"
          ansible_host: "{{ internal_ip }}"
          default_user: "domainadmin"
          default_password: "password"

    # Adding to existing service groups
    iis:
      hosts:
        IIS-Web:
          external_ip: "172.16.1.101"
          internal_ip: "172.20.11.101"
          ansible_host: "{{ internal_ip }}"
          default_user: "localuser"
          default_password: "password"

        IIS-FTP:
          external_ip: "172.16.1.104"
          internal_ip: "172.20.11.104"
          ansible_host: "{{ internal_ip }}"
          default_user: "localuser"
          default_password: "password"
    
    test:
      hosts:
        test_ubuntu:
          ansible_host: 10.1.1.11
          default_user: "sysadmin"
          default_password: "Changeme1!"
        test_rocky:
          ansible_host: 10.1.1.12
          default_user: "sysadmin"
          default_password: "Changeme1!"

    # --- Updated OS-based groups ---
    windows:
      children:
        ad_dns:
      hosts:
        IIS-Web:
        IIS-FTP:
        Win10-Wkst:

    rocky:
      children:
        webmail:
        siem:

    ubuntu:
      hosts:
        Ubuntu-Ecomm:
        Ubuntu-Wkst:

    linux:
      children:
        ubuntu:
        rocky:
      hosts:
        Alpine-FW:
        OPNsense-FW:

    inscope:
      children:
        ecomm:
        webmail:
        siem:
        windows: