---
- name: Populate Users
  hosts: all
  roles:
    - setup-boxes
  vars:
    lab_users:
      - { name: "twilight", admin: yes, lock: no, login: yes }
      - { name: "pinkie", admin: no, lock: no, login: yes }
      - { name: "dash", admin: no, lock: yes, login: no }
      - { name: "rarity", admin: yes, lock: no, login: no }
      - { name: "applejack", admin: no, lock: no, login: yes }
      - { name: "fluttershy", admin: no, lock: yes, login: no }
      - { name: "spike", admin: no, lock: no, login: no }
      - { name: "celestia", admin: yes, lock: no, login: yes }
      - { name: "luna", admin: yes, lock: yes, login: no }
      - { name: "derpy", admin: no, lock: no, login: yes }
  tags:
    - setup
    
- name: Deploy Birdsnest
  hosts: all
  roles:
    - birdsnest
  tags:
    - birdsnest
    - full

- name: Deploy Magpie
  hosts: all
  roles:
    - birdsnest-magpie
  tags:
    - magpie
    - full

- name: Deploy Owlet
  hosts: all
  roles:
    - birdsnest-owlet
  tags:
    - owlet
    - full

- name: Deploy Kingfisher
  hosts: all
  roles:
    - birdsnest-kingfisher
  tags:
    - kingfisher
    - full

- name: Apply Firewall Script
  hosts: inscope
  roles:
    - firewall
  tags:
    - firewall
    - full

- name: Backup Scored Services
  hosts: inscope
  roles:
    - backup
  tags:
    - backup
    - backups
    - full

- name: Lock unauthorized users
  hosts: inscope
  roles:
    - users_red
  tags:
    - users
    - users_red
    - full
  vars_prompt:
    - name: "new_password"
      prompt: "Enter the new password for all red Team accounts"
      private: no
      confirm: yes

- name: Add Blueteam Users
  hosts: inscope
  roles:
    - users_blue
  tags:
    - users
    - users_blue
    - full
  vars_prompt:
    - name: "new_password"
      prompt: "Enter the new password for all blue Team accounts"
      private: no
      confirm: yes

- name: Change password of inscope users
  hosts: inscope
  roles:
    - users_inscope
  tags:
    - users
    - users_inscope
    - full
  vars_prompt:
    - name: "new_password"
      prompt: "Enter the new password for all inscope Team accounts"
      private: no
      confirm: yes