---
# ansible-playbook magpie_playbook.yaml -i inventory.yaml -t magpie_server -vv
- name: Cleanup
  #hosts: ansible-controller
  hosts: active
  roles:
    - cleanup
  tags:
    - cleanup
    - full
    
- name: Deploy Magpie Server
  hosts: ansible-controller
  roles:
    - magpie_server
  tags:
    - magpie
    - magpie_server
    - owlet
    - owlet_server
    - full

- name: Deploy Magpie Client
  #hosts: iis-winserv22
  hosts: new-test-deb11
  #hosts: new-test-ubu24
  #hosts: new-test-rocky9
  #hosts: testing-deb12
  #hosts: testing-centos8
  #hosts: testing-rocky9
  #hosts: testing-alpine
  roles:
    - magpie_client
  tags:
    - magpie
    - magpie_client
    - full

- name: Deploy Owlet Client
  #hosts: iis-winserv22
  hosts: testing-ubu24
  #hosts: testing-deb12
  #hosts: testing-centos8
  #hosts: testing-rocky9
  #hosts: testing-alpine
  roles:
    - owlet
  tags:
    - owlet
    - owlet_client
    - full

- name: Deploy Magpie Client Automated (do not touch)
  hosts: all
  roles:
    - magpie_client
  tags:
    - magpie_client_auto

- name: Deploy Owlet Client Automated (do not touch)
  hosts: all
  roles:
    - owlet
  tags:
    - owlet_auto