# log.txt must be present before running!

services:
  nginx:
    image: nginx:1.28.2
    ports:
      - target: 443
        published: 443 #external
        protocol: tcp
        mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.pem:/etc/nginx/cert.pem:ro
      - ./key.pem:/etc/nginx/key.pem:ro
    depends_on:
      - webserver

  webserver:
    image: ghcr.io/ccdc-rit/birdsnest:latest
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - APP_CONTEXT=SERVER
    restart: unless-stopped
    command: ["gunicorn", "--bind", "0.0.0.0:80", "--workers", "1", "--worker-tmp-dir", "/dev/shm", "server:app"]
    deploy:
      replicas: 1
    depends_on:
      worker:
        condition: service_healthy
  
  worker:
    image: ghcr.io/ccdc-rit/birdsnest:latest
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - APP_CONTEXT=WORKER
    restart: unless-stopped
    command: ["python3", "worker.py"]
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/worker_ready"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 10s

  database:
    image: postgres:18.3
    restart: always
    environment:
      POSTGRES_USER: birdsnest
      POSTGRES_PASSWORD: birdsnestpwd
      POSTGRES_DB: birdsnestdb
    ports:
      - "5432:5432"
    volumes:
      #- pgdata:/var/lib/postgresql/data # <v18
      - pgdata:/var/lib/postgresql # >=v18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 3s
      timeout: 2s
      retries: 5

# docker volume ls; docker volume rm birdsnest_pgdata; docker volume ls; 
volumes:
  pgdata: