---
- name: Ensure destination directory exists
  ansible.windows.win_file:
    path: "{{ stabvest_deploy_dir }}"
    state: directory
  when: ansible_facts.os_family == "Windows" 

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ stabvest_deploy_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: ansible_facts.os_family != "Windows" 

- name: Copy agent executable to target
  win_copy:
    src: "files/{{ stabvest_agent_executable }}"
    dest: "{{ stabvest_deploy_dir }}\\{{ stabvest_agent_executable }}"
  when: ansible_facts.os_family == "Windows" 

- name: Render config.json from template
  template:
    src: "config.json.j2"
    dest: "{{ [stabvest_deploy_dir, 'config.json'] | path_join }}"

- name: Copy agent executable to target
  copy:
    src: "files/{{ stabvest_agent_executable }}"
    dest: "{{ stabvest_deploy_dir }}/{{ stabvest_agent_executable }}"
    owner: root
    group: root
    mode: '0755'
  when: ansible_facts.os_family != "Windows"

- name: Copy agent executable to target
  win_copy:
    src: "files/requirements.txt"
    dest: "{{ stabvest_deploy_dir }}\\requirements.txt"
  when: ansible_facts.os_family == "Windows" 

- name: Copy requirements to target
  copy:
    src: "files/requirements.txt"
    dest: "{{ stabvest_deploy_dir }}/requitements.txt"
    owner: root
    group: root
    mode: '0755'
  when: ansible_facts.os_family != "Windows"

- name: Create venv and install requirements
  ansible.builtin.pip:
    requirements: "{{ [{{ stabvest_deploy_dir }}, 'requirements.txt'] | path_join }}"
    virtualenv: "{{ [{{ stabvest_deploy_dir }}, 'venv'] | path_join }}"
    virtualenv_command: "{{ (ansible_os_family == 'Windows') | ternary('python -m venv', 'python3 -m venv') }}"
    state: present
  vars:
    base_dir: "{{ (ansible_facts.os_family == 'Windows') | ternary(stabvest_deploy_dir_win, stabvest_deploy_dir_unix) }}"

- name: Timestomp folder to evade detection
  win_shell: |
    $time = (Get-Item "C:\\Windows\\System32\\cmd.exe").CreationTime
    (Get-Item "{{ stabvest_deploy_dir }}").CreationTime = $time
    (Get-Item "{{ stabvest_deploy_dir }}").LastWriteTime = $time
    (Get-Item "{{ stabvest_deploy_dir }}").LastAccessTime = $time
  args:
    executable: "powershell.exe"
  when: ansible_facts.os_family == "Windows" 

- name: Timestomp agent to evade detection
  win_shell: |
    $time = (Get-Item "C:\\Windows\\System32\\cmd.exe").CreationTime
    (Get-Item "{{ stabvest_deploy_dir }}\\{{ stabvest_agent_executable }}").CreationTime = $time
    (Get-Item "{{ stabvest_deploy_dir }}\\{{ stabvest_agent_executable }}").LastWriteTime = $time
    (Get-Item "{{ stabvest_deploy_dir }}\\{{ stabvest_agent_executable }}").LastAccessTime = $time
  args:
    executable: "powershell.exe"
  when: ansible_facts.os_family == "Windows" 

- name: Timestomp config to evade detection
  win_shell: |
    $time = (Get-Item "C:\\Windows\\System32\\cmd.exe").CreationTime
    (Get-Item "{{ stabvest_deploy_dir }}\\config.json").CreationTime = $time
    (Get-Item "{{ stabvest_deploy_dir }}\\config.json").LastWriteTime = $time
    (Get-Item "{{ stabvest_deploy_dir }}\\config.json").LastAccessTime = $time
  args:
    executable: "powershell.exe"
  when: ansible_facts.os_family == "Windows" 

- name: Timestomp the folder
  command: touch -r /bin/sh {{ stabvest_deploy_dir }}
  when: ansible_facts.os_family != "Windows"

- name: Timestomp the agent
  command: touch -r /bin/sh {{ stabvest_deploy_dir }}/{{ stabvest_agent_executable }}
  when: ansible_facts.os_family != "Windows"

- name: Timestomp the config
  command: touch -r /bin/sh {{ stabvest_deploy_dir }}/config.json
  when: ansible_facts.os_family != "Windows"