---
- name: Ensure deployment directory exists
  file:
    path: "{{ stabvest_deploy_dir }}"
    state: directory
    mode: '0755'

- name: Ensure log.txt exists (preventing docker directory mapping error)
  file:
    path: "{{ stabvest_deploy_dir }}/log.txt"
    state: touch
    mode: '0755'

- name: Ensure repos/ exists (preventing docker directory mapping error)
  file:
    path: "{{ stabvest_deploy_dir }}/repos/"
    state: directory
    mode: '0755'

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "{{ stabvest_deploy_dir }}/"
  with_items:
    - models.py
    - requirements.txt
    - server.py
    - shared.py
    - utilities.py
    - worker.py
    - agents
    - modules
    - static
    - templates

- name: Deploy Nginx config file
  template:
    src: nginx.conf.j2
    dest: "{{ stabvest_deploy_dir }}/nginx.conf"

- name: Deploy Dockerfile Server
  template:
    src: Dockerfile-server.j2
    dest: "{{ stabvest_deploy_dir }}/Dockerfile-server"

- name: Deploy Dockerfile Worker
  template:
    src: Dockerfile-worker.j2
    dest: "{{ stabvest_deploy_dir }}/Dockerfile-worker"

- name: Deploy Docker Compose config file
  template:
    src: docker-compose.yaml.j2
    dest: "{{ stabvest_deploy_dir }}/docker-compose.yaml"

- name: Deploy webserver config file
  template:
    src: config.json.j2
    dest: "{{ stabvest_deploy_dir }}/config.json.yaml"

- name: Ensure OpenSSL is installed
  package:
    name: openssl
    state: present

- name: Generate self-signed SSL Certificate
  command: >
    openssl req -x509 -newkey rsa:4096 -nodes
    -keyout {{ stabvest_deploy_dir }}/key.pem
    -out {{ stabvest_deploy_dir }}/cert.pem
    -days 365
    -subj "/CN={{ stabvest_host }}"
  #openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365 -subj "//CN=127.0.0.1" # WINDOWS
  args:
    creates: "{{ stabvest_deploy_dir }}/cert.pem"

- name: Pull and Build Docker Images
  community.docker.docker_compose_v2:
    project_src: "{{ stabvest_deploy_dir }}"
    build: always
    state: present