- name: Ensure Local Backup Directory Exists
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ controller_backup_root }}"
    state: directory
    mode: '0700'

- name: Windows | Process Protected Folders
  ansible.builtin.include_tasks: windows.yaml
  when: ansible_os_family == "Windows"
    
- name: Linux | Process Protected Folders
  ansible.builtin.include_tasks: linux.yaml
  when: ansible_os_family != "Windows"